spring:
  application:
    name: scm2.0
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASSWORD}
  #jpa configurations
  jpa:
    show-sql: ${SHOW_SQL:true}
  #for creating schemas and tables
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}
  profiles:
    active: ${ACTIVE_PROFILE:dev}
server:
  baseUrl: ${BASE_URL}
  port: ${SERVER_PORT:8081}